const itemFeatureHeaders = Array.from(
  { length: 20 },
  (_, index) => `ITEM_FEATURES_${index + 1}`
);

const attributeHeaders = Array.from({ length: 50 }, (_, index) => [
  `ATTRIBUTE_LABEL ${index + 1}`,
  `ATTRIBUTE_VALUE ${index + 1}`,
  `ATTRIBUTE_UOM ${index + 1}`,
]).flat();

/**
 * The UniHack delivery contract. The source template requires every header to
 * remain present, in this exact spelling and sequence, even when a value is blank.
 */
export const UNIHACK_DELIVERY_HEADERS = [
  "MFR URL",
  "Ref URL 1",
  "Ref URL 2",
  "Ref URL 3",
  "Ref URL 4",
  "Ref URL 5",
  "PART_NUMBER",
  "Dept",
  "Class",
  "Fine",
  "SKU - MY_PART_NUMBER",
  "Mfg_Part_Num",
  "Part_Desc",
  "E1_Brand",
  "Unilog_Brand",
  "DIB_Brand",
  "Part_Manuf",
  "MANUFACTURER_NAME",
  "BRAND_NAME",
  "TRADE_NAME",
  "MANUFACTURER_PART_NUMBER",
  "ALTERNATE_PART_NUMBER",
  "Classpath",
  "MOBILE_DESC",
  "INVOICE_DESC",
  "SHORT_DESC",
  "LONG_DESC1",
  "RETAIL_DESC",
  "MARKETING_DESCRIPTION",
  ...itemFeatureHeaders,
  "With",
  "Standard/Approvals",
  "Prop 65",
  "Application",
  "Includes",
  "Product Name",
  ...attributeHeaders,
  "UPC",
  "EAN",
  "GTIN",
  "UNSPSC",
  "Warranty",
  "List Price",
  "Selling Qty",
  "Selling UOM",
  "Standard Packaging Information",
  "LENGTH",
  "LENGTH_UOM",
  "HEIGHT",
  "HEIGHT_UOM",
  "WIDTH",
  "WIDTH_UOM",
  "WEIGHT",
  "WEIGHT_UOM",
  "VOLUME",
  "VOLUME_UOM",
  "Product Image",
  "Alternate Image 1",
  "Alternate Image 2",
  "Alternate Image 3",
  "Alternate Image 4",
  "SDS",
  "SDS_1",
  "Warranty Information",
  "Catalog",
  "Specification Sheet",
  "Instruction/Installation Manual",
  "Service Manual",
  "Owners/User Manual",
  "Line Drawing",
  "MTR",
  "RoHS",
  "Full Engineering Drawing",
  "Energy Star Guide",
  "Technical Bulletin",
  "Submittal",
  "Compatibility Chart",
  "Size Chart",
  "Product Label/Insert",
  "Video Link",
  "Video Link 1",
  "Country Of Origin",
  "Discontinued",
  "Actual Image (Yes/No)",
] as const;

export type UnihackDeliveryHeader = (typeof UNIHACK_DELIVERY_HEADERS)[number];
export type UnihackDeliveryRow = Record<UnihackDeliveryHeader, string>;
